Repository fusionjs/fusion-rpc-redux, pull requests merged in 2018-11, with the labels that each got.

#141 Add initalArgs to error payload
  src/__tests__/index.node.js
  src/index.js
Labels: feature

#142 Release v1.3.0
  package.json
Labels: release

#143 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#145 Update error handling to bubble errors that occur in reducers
  src/__tests__/index.node.js
  src/index.js
Labels: bugfix
