Repository fusionjs/fusion-rpc-redux, pull requests merged in 2018-10, with the labels that each got.

#129 Allow mapStateToProps to amend existing rpc arguments
  src/__tests__/index.node.js
  src/index.js
Labels: feature

#131 Release v1.2.0
  package.json
Labels: release

#133 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#138 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor
