Repository fusionjs/fusion-rpc-redux, pull requests merged in 2019-02, with the labels that each got.

#154 Do not restore the promise chain on error, instead continue errors
  src/__tests__/index.node.js
  src/index.js
Labels: bugfix

#159 Release v1.4.0-1
  package.json
Labels: release

#160 Release v1.4.0
  package.json
Labels: release

#162 Upgrade flow and remove useless flow lib config
  .flowconfig
  package.json
  yarn.lock
Labels: refactor

#164 Revert #154
  src/__tests__/index.node.js
  src/index.js
Labels: bugfix

#165 Release v1.4.1-0
  package.json
Labels: release

#167 Release v1.4.1
  package.json
Labels: release
